EcommerceBundle\Entity\Product:
    type: entity
    table: products
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        price:
            type: integer
            nullable: false
            options:
                unsigned: false
        stock:
            type: integer
            nullable: false
            options:
                unsigned: false
    manyToMany:
        idorder:
            targetEntity: Order
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: idproduct
            joinTable:
                name: productorders
                joinColumns:
                    -
                        name: idProduct
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: idOrder
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
